version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  networks:
    - spring-network
  image: mysql:5.7
  restart: unless-stopped
  environment:
    - MYSOL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=tpachat
  ports:
    - "3306:3306"
  volumes:
    - db:/home/mysql/data:/var/lib/mysql
 spring_app:
  image: eya25/achat
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
  environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpachat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
  volumes:
    - m2:/home/mysql/data:/var/lib/application
  depends_on:
    - mysqldb
  networks:
    - spring-network  
networks:
  spring-network:
   name: spring-network    
volumes:
  m2:
  db:   
