version: "3.7"

services:

  app:
    build:
      context: "./"
      dockerfile: Dockerfile
    image: youssef2404/youssef
    container_name: achat
    depends_on:
      - dbSpring
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://dbSpring:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
            "spring.datasource.username" : "youssef",
            "spring.datasource.password" : "",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'

  dbSpring:
    image: mysql:5.7
    restart: unless-stopped
    container_name: dbSpring  
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
      
      
      
   



