version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=achatdb
    ports:
      - - 3306:3306
    volumes:
      - achatdb:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./spring-app
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
       SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://dbSpring:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
            "spring.datasource.username" : "youssef",
            "spring.datasource.password" : "",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
