version: "3.7"

services:

  app:
    image: youssef2404/youssef
    restart: on-failure
    container_name: achat
    depends_on:
      - dbSpring
    ports:
      - 8089:8089
    
  dbSpring:
    image: mysql:5.7
    restart: unless-stopped
    container_name: dbSpring
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql

