version: "3.3"

services:
 mysqldb:
  container_name: mysqldb
  image: mysql:8
  restart: unless-stopped
  environment:
   MYSOL_ROOT_PASSWORD: root
  ports:
    - "3306:3306"
  volumes:
    - /home/mysql/data:/var/lib/mysql
 spring_app:
  image: eya25/achat-1.0
  container_name: achat
  restart: on-failure
  ports:
    - 8089:8089
  depends_on:
    - mysqldb