version: "3.7"

services:

  app:
    working_dir: /spring-app
    build:
      context: .
      dockerfile: Dockerfile
    image: eya25/achat
    restart: on-failure
    container_name: achat
    depends_on:
      - dbSpring
    networks:
      - spring-network
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://dbSpring:3306/dbachat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExists=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    volumes:
      - .m2:/root/maven-repo
    stdin_open: true
    tty: true


  dbSpring:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    container_name: dbSpring
    networks:
      - spring-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbachat
    ports:
      - 3306:3306
    volumes:
      - tpstockdb:/var/lib/mysql

networks:
  spring-network:
    name: spring-network

volumes:
  .m2:
  tpstockdb:
  
